name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shop:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/shop:$IMAGE_TAG
          docker tag ${{ secrets.DOCKER_USERNAME }}/shop:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/shop:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/shop:latest

      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./docker-compose.yml"
          target: "~"

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~
            sudo docker compose down
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/shop:latest
            sudo docker compose up -d
            sudo docker image prune -f
